-- 코드를 작성해주세요
SELECT C.ID,
C.GENOTYPE,
P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS C
LEFT JOIN ECOLI_DATA AS P
ON P.ID = C.PARENT_ID
WHERE (C.GENOTYPE & P.GENOTYPE) = P.GENOTYPE
ORDER BY ID ASC;